spring.application.name=commerce-payment-system
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.config.import=optional:file:.env[.properties]

portone.base-url=https://api.portone.io
portone.api-secret=${PORTONE_API_SECRET:}
portone.store-id=${PORTONE_STORE_ID:}
portone.channel-key=${PORTONE_CHANNEL_KEY:}
