spring.application.name=commerce-payment-system
spring.profiles.active=local
spring.config.import=optional:file:.env[.properties]

# Common PortOne configs
portone.base-url=https://api.portone.io
portone.api-secret=${PORTONE_API_SECRET:}
portone.store-id=${PORTONE_STORE_ID:}
portone.channel-key=${PORTONE_CHANNEL_KEY:}
portone.webhook-secret=${PORTONE_WEBHOOK_SECRET:}

# JWT Configuration
jwt.secret=${JWT_SECRET:defaultSecretKeyForLocalTestingWhichNeedsToBeAtLeast32BytesLong}
jwt.access.token.expiration=${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
jwt.refresh.token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION:1209600000}
