# Local Environment Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/commerce}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Local JPA settings (Creates DB schema automatically, shows SQL)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Initialize DB with data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
